//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HobbiesMVC.HobbiesServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HobbiesServices.IHobbies")]
    public interface IHobbies {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHobbies/registrarHobby", ReplyAction="http://tempuri.org/IHobbies/registrarHobbyResponse")]
        void registrarHobby(int codigo, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHobbies/listarHobbies", ReplyAction="http://tempuri.org/IHobbies/listarHobbiesResponse")]
        int[] listarHobbies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHobbies/obtenerDescripcionHobby", ReplyAction="http://tempuri.org/IHobbies/obtenerDescripcionHobbyResponse")]
        string obtenerDescripcionHobby(int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHobbiesChannel : HobbiesMVC.HobbiesServices.IHobbies, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HobbiesClient : System.ServiceModel.ClientBase<HobbiesMVC.HobbiesServices.IHobbies>, HobbiesMVC.HobbiesServices.IHobbies {
        
        public HobbiesClient() {
        }
        
        public HobbiesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HobbiesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HobbiesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HobbiesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void registrarHobby(int codigo, string descripcion) {
            base.Channel.registrarHobby(codigo, descripcion);
        }
        
        public int[] listarHobbies() {
            return base.Channel.listarHobbies();
        }
        
        public string obtenerDescripcionHobby(int codigo) {
            return base.Channel.obtenerDescripcionHobby(codigo);
        }
    }
}
